version: 2.1

jobs:
  run-tests:
    docker:
      - image: catalinkubeshop/testkube-testing:latest
    # working_directory: /home/testkube
    steps:
      - run:
          name: "Set Testkube Context"
          command: "testkube set context --api-key $TESTKUBE_API_KEY --org $TESTKUBE_ORG_ID --env $TESTKUBE_ENV_ID --cloud-root-domain testkube.dev"
      - run:
          name: "Trigger testkube test"
          command: "testkube run test curl-test3 -f"

workflows:
  run-tests-workflow:
    jobs:
      - run-tests
