version: 2.1

jobs:
  run-tests:
    docker:
      - image: kubeshop/testkube-cli
    working_directory: /home/testkube
    # environment:
    #   TESTKUBE_ORG_ID: ""
    #   TESTKUBE_ENV_ID: ""
    #   TESTKUBE_API_KEY: ""
    steps:
      - run:
          name: "Set Testkube Context"
          command: "kubectl-testkube set context --api-key $TESTKUBE_API_KEY --org $TESTKUBE_ORG_ID --env $TESTKUBE_ENV_ID"
      - run:
          name: "Trigger testkube test"
          command: "kubectl-testkube run test curl-test1 -f"

workflows:
  run-tests-workflow:
    jobs:
      - run-tests
